### ISSUE TITLE
connect with PRIVATE KEY

### ISSUE THREAD

**Issue by sedghian** [ashraf789/Cake-VPN#38]
hi . i thank you for this source code .
 my problem is connecting with PRIVATE KEY in openvpn .
how to use "PRIVATE KEY" instead "user / password"?

**Comment by ashraf789** [comment]
Hello,
You could select  PRIVATE KEY instead of user/password . I didn't try before but you could do it something like this.
Use VPNLaunchHelper.startOpenVpn(VpnProfile startprofile, Context context) instead of OpenVpnApi.startVpn(....) class 
When you prepare VpnProfile object, select certificates instead user/pw

Hope you could achieve what you want.
